### ISSUE TITLE
Add support for filesystem type for volume reouserce

### ISSUE THREAD

**Issue by pgrzesik** [terraform-providers/terraform-provider-digitalocean#103]
### Terraform Version
v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_volume

### Expected Behavior
I should be able to specify `FilesystemType` for created volume resources.

### Actual Behavior
`FilesystemType` is not configurable for volumes.

### Proposal
My proposal would be to accept additional flag, that will add support for configuring `FilesystemType` of created volumes. I checked and it's supported in `godo` (https://github.com/digitalocean/godo/blob/master/storage.go). If I get a green light, I think I can take a stab at implementing it.

Regards, Piotr

**Comment by pgrzesik** [comment]
Related PR: https://github.com/terraform-providers/terraform-provider-digitalocean/pull/111

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
