### ISSUE TITLE
CAA record support

### ISSUE THREAD

**Issue by felnne** [terraform-providers/terraform-provider-digitalocean#110]
Hi,

I'm trying to create a CAA record but this doesn't seem to be supported by the Terraform DO record resource. Specifically options for `tag` and `flag` seem to be missing, which are required by the DO API.

I don't get an error for an invalid record type which I assume means it should be supported? Is there just a different syntax I need to use?

### Terraform Version

Terraform v0.11.3
+ provider.digitalocean v0.1.3

### Affected Resource(s)

- digitalocean_record

### Terraform Configuration Files
```hcl
resource "digitalocean_record" "example-caa-issue" {
  domain = "example.com"
  type   = "CAA"
  name   = "${digitalocean_droplet.stage-lb1.name}"
  value  = "0 issue \"letsencrypt.org\""
}
```

### Expected Behavior
What should have happened?

A CAA record is created.

### Actual Behavior
What actually happened?

```
Error: Error applying plan:

* digitalocean_record.example-caa-issue: 1 error(s) occurred:

* digitalocean_record.example-caa-issue: Failed to create record: POST https://api.digitalocean.com/v2/domains/example.com/records: 422 Flags is not a number, Flags must be an integer between 0 and 255, and Tag must be issue, issuewild, or iodef
```

### Steps to Reproduce

1. `terraform apply`

**Comment by andrewsomething** [comment]
Support for CAA records was added in https://github.com/terraform-providers/terraform-provider-digitalocean/pull/48. It will be part of the next release.

**Comment by felnne** [comment]
@andrewsomething - ah ok, do you know when that will be?

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
