### ISSUE TITLE
Custom Firewall Rules Overriden or Not Created

### ISSUE THREAD

**Issue by carlapcastro** [terraform-providers/terraform-provider-digitalocean#113]
Hi there,

I'm trying to create a DigitalOcean firewall with custom inbound and outbound rules. However, it seems that if I want to create a rule that allows ingress/egress on ports other than 80, 443, 22, 53, the rule is either overwritten with one of those ports or its not added as part of the configuration. 

### Terraform Version
0.11.7

### Affected Resource(s)
- digitalocean_firewall

### Terraform Configuration Files
```hcl
data "http" "cloudflare_ipv4" {
  url = "https://www.cloudflare.com/ips-v4"
}

data "http" "cloudflare_ipv6" {
  url = "https://www.cloudflare.com/ips-v6"
}

resource "digitalocean_firewall" "forum" {
  name = "forum"

  droplet_ids = ["${digitalocean_droplet.forum.id}"]

  inbound_rule = [
    {
      protocol   = "tcp"
      port_range = "443"

      source_addresses = [
        "${split("\n",trimspace(data.http.cloudflare_ipv4.body))}",
        "${split("\n",trimspace(data.http.cloudflare_ipv6.body))}",
      ]
    },
    {
      protocol   = "tcp"
      port_range = "24756"
      source_addresses = ["0.0.0.0/0", "::/0",]
    },
  ]

  # allow all egress
  outbound_rule = [
    {
      protocol              = "tcp"
      port_range            = "1-65535"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
    {
      protocol              = "udp"
      port_range            = "1-65535"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
  ]
}

```

### Expected Behavior
Terraform should create a firewall as specified in the configuration.

### Actual Behavior
Terraform produces the following plan where it doesn't write the rule opening up port `24756` and it overwrites the rules for allowing all egress to port `53`:
![image](https://user-images.githubusercontent.com/3248491/42969596-90b59bf2-8b5b-11e8-8b6c-957c4e752448.png)

### Steps to Reproduce
1. `terraform plan` on the terraform configuration above along with the configuration for the digitalocean provider.

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
