### ISSUE TITLE
import a droplet and apply cause an unneeded droplet resize

### ISSUE THREAD

**Issue by caarlos0** [terraform-providers/terraform-provider-digitalocean#126]
### Terraform Version

```
Terraform v0.11.8
+ provider.digitalocean v0.1.3
```

### Affected Resource(s)
- digitalocean_droplet

### Terraform Configuration Files
```hcl
variable "digitalocean_token" {}

provider "digitalocean" {
  token = "${var.digitalocean_token}"
}

resource "digitalocean_droplet" "becker-test" {
  image    = "ubuntu-16-04-x64"
  region   = "sfo2"
  size     = "s-1vcpu-1gb"
  name     = "becker-test"
}

```

### Debug Output
noop

### Panic Output
noop

### Expected Behavior
In place change without any resizes.

### Actual Behavior
Droplet was resized to the same size it already was.

### Steps to Reproduce
1. `terraform import digitalocean_droplet.becker-test ID`
2. `terraform apply`

### Important Factoids

If I set `resize_disk = "false"` in the HCL, it works as expected.

### References

noop

**Comment by andrewsomething** [comment]
Thanks for the report. This behaviour was due to the fact that no default value was being set in the state file on import for `resize_disk`. The provider defaults to `resize_disk = "true"` for new resources, so when it is not set in the state file it attempts to rectify that. This was fixed in #95 and will be in the next release.

**Comment by caarlos0** [comment]
any ETA for the release?

**Comment by caarlos0** [comment]
not sure if fixed, but I also noticed that sometimes the `image` field is not imported...
