### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by liztio** [terraform-providers/terraform-provider-digitalocean#142]
We've got a lot of issues marked "fixed-in-master." I know I've been using the master release to set up infrastructure, and it'd sure be easier to use if there was a 1.4

@andrewsomething looks like you're our maintainer, how about it?

**Comment by andrewsomething** [comment]
Good news folks: Barring any surprises, we'll be looking to cut a new release later this week. I know it's long overdue. We want to land #115 as well since this is another big pain point. Once that's in, we'll coordinate w/ HashiCorp on the actual release.

**Comment by caarlos0** [comment]
Cool! 🚀

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

Thanks for your patience!
