### ISSUE TITLE
Importing droplet will try to generate resize_disk attribute

### ISSUE THREAD

**Issue by txomon** [terraform-providers/terraform-provider-digitalocean#143]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
$ terraform -v
Terraform v0.11.8
+ provider.digitalocean v0.1.3
```

### Affected Resource(s)
- digitalocean_droplet

### Terraform Configuration Files
```hcl
resource "digitalocean_droplet" "project_droplet" {
  name   = "somemachine-ubuntu-512mb-lon1-01"
  region = "lon1"
  size   = "512mb"
  image  = ""
```

### Expected Behavior
After importing the resource properly, there should be no changes

### Actual Behavior
However terraform wants to change it:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ digitalocean_droplet.project_droplet
      resize_disk: "" => "false"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
1. `terraform import digitalocean_droplet.project_droplet 123456789`
2. `terraform plan`

### Important Factoids
May this be because the upgrades DO did for free (machines before had less of everything IIRC) and this machine was created long ago.

### Workaround
```
resource "digitalocean_droplet" "project_droplet" {
  name   = "somemachine-ubuntu-512mb-lon1-01"
  region = "lon1"
  size   = "512mb"
  image  = ""

  lifecycle = {
    ignore_changes = "resize_disk"
  }
}
```

**Comment by andrewsomething** [comment]
Thanks for the report. This issue occurs since the `resize_disk` attribute was not being set during import, but the provider defaults to `resize_disk = true`.

Rather than ignoring changes, you can set it to the value you'd like. This attribute controls whether the disk size of a Droplet will be increased or not when resizing the Droplet. This is an important consideration as once you increase a Droplet's disk size you can not shrink it again. So use `resize_disk = false` when you want to be able to scale up your CPU and RAM temporarily and scale back down latter. Use `resize_disk = true` if you'd like to permanently scale your Droplet up to a new size.

There is a fix in master which should be released later this week. It sets `resize_disk = true` when importing to match the default behaviour:

https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/resource_digitalocean_droplet.go#L354

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
