### ISSUE TITLE
Equivalent of aws_s3_bucket_object data source for spaces ?

### ISSUE THREAD

**Issue by aboeglin** [terraform-providers/terraform-provider-digitalocean#176]
Hi everyone,

I wanted to know if there's any plan on adding a data source that does the same as aws_s3_bucket_object ? Or is there any was to directly use aws_s3_bucket_object maybe ? I know it's possible to setup a terraform backend with spaces already. Anyone had success with it ?

**Comment by lfarnell** [comment]
Once PR(#77) is merged, you will be able to create a DO space but I don’t think anyone has requested a data source. The aws_s3_bucket_object most likely wouldn’t work due to the fact that you would have to plug in aws credentials and you would be able to point it to a bucket location outside of AWS. Seems like a valid use case though.

**Comment by aboeglin** [comment]
For now I used ansible just to fetch the 2 files I needed in terraform, I then run terraform and delete the files afterwards. Having it all within terraform would feel more natural I guess.

**Comment by slapula** [comment]
#77 will introduce the necessary components that will make writing the data source fairly easy (from what I can tell so far) and I can take a shot at it once my PR is merged.

**Comment by tdyas** [comment]
https://github.com/terraform-providers/terraform-provider-digitalocean/pull/423 adds a `digitalocean_spaces_bucket_object` data source. v1.17.0 includes it. This issue can probably be closed.
