### ISSUE TITLE
Add support for adding CORS to digitalocean_spaces. 

### ISSUE THREAD

**Issue by IAmNatch** [terraform-providers/terraform-provider-digitalocean#254]
### Terraform Version
Terraform v0.11.13-0.12.12
+ provider.digitalocean v1.4.0

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_space_bucket

### Proposed feature
Provide the ability to set a spaces CORS policy. It's already accessible via the DO api. 

### References
https://developers.digitalocean.com/documentation/spaces/#set-bucket-cors

**Comment by IAmNatch** [comment]
Could someone point me in the right direction for a contribution?

**Comment by andrewsomething** [comment]
Since we are using aws-sdk-go to interact with the Spaces API, the code would look quite similar to how it is implemented in the `aws_s3_bucket` resource. If you wanted to work on this, it's probably a good starting place.

Schema: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_s3_bucket.go#L81-L112
