### ISSUE TITLE
No client_certificate,client_key when creating k8s cluster

### ISSUE THREAD

**Issue by botzill** [terraform-providers/terraform-provider-digitalocean#310]
### Terraform Version
```Terraform v0.12.10```

### Terraform Configuration Files
```hcl
# Configure the DigitalOcean Provider
provider "digitalocean" {
  token   = var.do_token
  version = "~> 1.8"
}

resource "digitalocean_kubernetes_cluster" "k8s" {
  name    = "k8s-${var.env}-${var.do_region}"
  region  = var.do_region
  version = var.k8s_version

  node_pool {
    name       = "k8s-${var.env}-${var.do_region}-worker-pool"
    size       = var.do_droplet_size
    node_count = var.k8s_node_count
    tags = [
      "k8s-${var.env}",
      var.do_region,
      "k8s",
    ]
  }

  lifecycle {
    ignore_changes = [node_pool[0].tags]
  }
}
```

### Expected Behavior
I see no `kube_config[0].client_certificate` and `kube_config[0].client_key`.

My output is

```hcl
output "k8s_client_certificate" {
  value = digitalocean_kubernetes_cluster.k8s.kube_config[0].client_certificate
}

output "k8s_client_key" {
  value = digitalocean_kubernetes_cluster.k8s.kube_config[0].client_key
}
```

What should have happened?

Should get this values.

### Actual Behavior
What actually happened?

Empty field for those values.

**Comment by snormore** [comment]
Hi there 👋 

DOKS configurations now include tokens for authentication instead of certificates. Based on your example output, you'll want to do something like this:

```tf
output "k8s_token" {
  value = digitalocean_kubernetes_cluster.k8s.kube_config[0].token
}
```

**Comment by botzill** [comment]
I see, but seems that there is no `token` returned  in `kube_config`. I see it in `raw_config` under `users`. is that OK?

**Comment by andrewsomething** [comment]
Due to recent in DigitalOcean Kubernetes, new clusters return a token for authentication rather than a certificate pair. The change exposing the `token` attribute was added in https://github.com/terraform-providers/terraform-provider-digitalocean/pull/309 and will be part of the v1.9.0 release. I've asked the team a HashiCorp to kick off a new release. I will update this issue when the release is available. In the meantime, the token shown in `raw_config` can be used. 

For more details on the recent DigitalOcean Kubernetes changes, see:

https://blog.digitalocean.com/new-on-digitalocean-kubernetes/
https://www.digitalocean.com/docs/kubernetes/how-to/connect-to-cluster/#automatically-managed-tokens-recommended

Sorry for the inconvenience!

**Comment by botzill** [comment]
Thx @andrewsomething for update. I did try `token` from user section but seems to not work with `kubernetes` provider. For now I will stick with 

```hcl
provider "kubernetes" {
  version = "~> 1.9"
  config_path = data.terraform_remote_state.s3.outputs.config_filename
  load_config_file = true
}
```

until new release 
Thx!

**Comment by andrewsomething** [comment]
The new release should now be available with:

    terraform init -upgrade

Please let us know if you run into any other issues.
