### ISSUE TITLE
fqdn for the record doesn't match DO

### ISSUE THREAD

**Issue by abitrolly** [terraform-providers/terraform-provider-digitalocean#51]
When generating record with the following file:
```
resource "digitalocean_record" "mars" {
  domain     = "cyber.fund"
  type       = "A"
  name       = "mars.cyber.fund"
  value      = "93.125.26.210"
}
```
`terraform show` then outputs `mars.cyber.fund` as fqdn:
```
digitalocean_record.mars:
  id = 29299392
  domain = cyber.fund
  fqdn = mars.cyber.fund
  name = mars.cyber.fund
...
```
But DigitalOcean records it is `mars.cyber.fund.cyber.fund`.

### Terraform Version
v.10.7

### Affected Resource(s)
- digitalocean_record

**Comment by danrabinowitz** [comment]
Try changing "name = mars.cyber.fund" to "name = "mars"

**Comment by abitrolly** [comment]
Already done. It is still convenient to have greppable `mars.cyber.fund` name directly in the config.

**Comment by danrabinowitz** [comment]
I understand. The way DNS works is that a record has a "name" of "mars" in the domain of "cyber.fund". That's just part of DNS, not terraform.

**Comment by abitrolly** [comment]
`terraform` should set the value to `mars.cyber.fund.cyber.fund` then. This test doesn't match DO behaviour:

https://github.com/terraform-providers/terraform-provider-digitalocean/blob/e74650b26671816037a8275767f1bca42327db19/resource_digitalocean_record_test.go#L24

**Comment by abitrolly** [comment]
For usability sake I would make `fqdn` field writable and mutually exclusive with `name` to reuse the helper https://github.com/terraform-providers/terraform-provider-digitalocean/blob/e74650b26671816037a8275767f1bca42327db19/resource_digitalocean_record.go#L209

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
