### ISSUE TITLE
digitalocean_droplet resource should probably use hash for user_data

### ISSUE THREAD

**Issue by jcassee** [terraform-providers/terraform-provider-digitalocean#65]
When using `plan` or `apply`, the `aws_instance` resource uses the hash of the `user_data` attribute. Instead the `digitalocean_droplet` resources displays the value itself. The value can become very and might contain sensitive data. 

Compare [resource_digitalocean_droplet.go](https://github.com/terraform-providers/terraform-provider-digitalocean/blob/310d4ec82ea7bda0315ae56788b0465db6fd879c/digitalocean/resource_digitalocean_droplet.go#L144) and [resource_aws_instance.go](https://github.com/terraform-providers/terraform-provider-aws/blob/b82247b1d1270097aaf1e746749d958525bbdff5/aws/resource_aws_instance.go#L106).

Unfortunately, I know too little Go to create a pull request myself.

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!

**Comment by jcassee** [comment]
Great, thanks @andrewsomething!
