### ISSUE TITLE
Terraform fails with Golang JSON parsing error if tag name is invalid

### ISSUE THREAD

**Issue by jstangroome** [terraform-providers/terraform-provider-digitalocean#78]
terraform v0.11.1
digitalocean provider v0.1.3

### Affected Resource(s)
- digitalocean_tag

### Terraform Configuration Files
```hcl
provider "digitalocean" {
  version = "~> 0.1.3"
}

resource "digitalocean_tag" "bad_tag" {
  name = "bad.tag.name"
}
```

### Debug Output
```
digitalocean_tag.bad_tag: Creating...
  name: "" => "bad.tag.name"

Error: Error applying plan:

1 error(s) occurred:

* digitalocean_tag.bad_tag: 1 error(s) occurred:

* digitalocean_tag.bad_tag: Error creating tag: invalid character 'S' looking for beginning of value
```

### Expected Behavior
If a tag name with unsupported characters is specified for a digitalocean_tag in Terraform, validation should report the cause of the issue with a actionable error message (eg dot is not a support character).

### Actual Behavior
Provider propagated an unhelpful Golang JSON parser error message as a result of an unexpected API response.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
