### ISSUE TITLE
Changing the size of a volume tries to delete it instead of resize

### ISSUE THREAD

**Issue by turt2live** [terraform-providers/terraform-provider-digitalocean#82]
### Terraform Version
```
$ terraform -v
Terraform v0.11.5
+ provider.digitalocean v0.1.3
```

### Terraform Configuration Files
```hcl
resource "digitalocean_volume" "pg_vol" {
  name        = "pgdata"
  region      = "lon1"
  size        = 20 
  description = "postgres data volume"
}

resource "digitalocean_droplet" "postgres" {
  image              = "ubuntu-16-04-x64"
  name               = "postgres"
  region             = "lon1"
  size               = "1gb"
  volume_ids         = ["${digitalocean_volume.pg_vol.id}"]
}
```

### Expected Behavior
The volume should be resized.

### Actual Behavior
The volume tries to get deleted.

```
  ~ digitalocean_droplet.postgres
      volume_ids.#:                      "1" => <computed>

-/+ digitalocean_volume.pg_vol (new resource required)
      id:                                "resource_uuid_goes_here" => <computed> (forces new resource)
      description:                       "postgres data volume" => "postgres data volume"
      droplet_ids.#:                     "1" => <computed>
      name:                              "pgdata" => "pgdata"
      region:                            "lon1" => "lon1"
      size:                              "20" => "30" (forces new resource)
```

Going through with this plan will lead to a 409 error: Volume needs to be detached first.

### Steps to Reproduce
1. `terraform apply`
2. Change the `size` on the `digitalocean_volume` (`pg_vol` in this case)
3. `terraform apply`

**Comment by andrewsomething** [comment]
Thanks for reporting this issue. Unfortunately, Terraform does not currently support resizing volumes:

https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/resource_digitalocean_volume.go#L48

While this is definitely something we should support, we should at least document the existing state.

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
