### ISSUE TITLE
Free certificates with LetsEncrypt

### ISSUE THREAD

**Issue by danihodovic** [terraform-providers/terraform-provider-digitalocean#93]
The DO API now provides a way to automatically create certificates with LetsEncrypt which can be used in load balancers.

All that needs to be provided is `type: "lets_encrypt"` instead of `private_key`, `leaf_certificate` and `certificate_chain`. The change does not look very complicated and I was wondering if there are any plans in the near term to implement this. If not, I could have a stab at it.

https://developers.digitalocean.com/documentation/v2/#certificates

**Comment by holms** [comment]
This is something I'm really looking for. Because of this feature absence, I'm using traefik to do this job, but it's a bit overkill.

**Comment by holms** [comment]
@andrewsomething when you'll do a release :)? it's almost 1  year from the last one.

**Comment by andrewsomething** [comment]
@holms A release is long overdue. We'll be looking to cut a new one in the very near future, but we have a few more improvements that we want to get to first. I hope the recent commit history shows that we're committed (pun intended) to bringing some much needed love to the project.

**Comment by holms** [comment]
Andrew you got all my love in here :)

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
